version: '3.8'

services:
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - redis_data:/data
  celery:
    build: ./app
    command: celery -A project worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_proj
      - POSTGRES_PASSWORD=my_proj
      - POSTGRES_DB=my_proj_dev

volumes:
  postgres_data:
  redis_data:

