# Generated by Django 3.2 on 2022-10-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, help_text='Только для авторизованных', max_length=50, null=True),
        ),
    ]
