# Generated by Django 3.2 on 2022-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
